### PR TITLE
General content update

### LINKED ISSUE #54: add your Alternate authentication credentials to pool
In 12.1, you indicate "add your Alternate authentication credentials add your Alternate authentication credentials", this is not feasible
I go to control panel, click on the linux pool, then Roles, I have as mentioned 
"Agent Pool Administrators" and 
Agent Pool Service Account", 
in both I have my primary user but when I try to add the alternate one, I get a message
 " **No identities found**".
Can you please let me know how this can be achieved? Thanks

### PR DESCRIPTION
**Pull request by OguzPastirmaci**
This is a general update to the content.

Closes #54

### CODE REVIEW

**Comment by dtzar** [comment]
Why are you getting rid of these files?
image

**Comment by OguzPastirmaci** [comment]
They are either duplicates or not used in the labs except for the Integration Services one. I'll add an updated version soon.

**Comment by dtzar** [comment]
Per our discussion:
- rename DockerizationAndWhy to remove all the "why" references and move it under Docker deploy
- keep IaC HOL, just make sure technically ok
- keep Integration Services and just update this when you have updates ready

**Comment by OguzPastirmaci** [comment]
Made the changes ds per our discussion.

This will:

- rename DockerizationAndWhy to remove all the "why" references and move it under Docker deploy
- keep IaC HOL, just make sure technically ok
- keep Integration Services and just update this when you have updates ready

also:

- add Microsoft code of conduct
- update the steps in several HOLs to reflect changes in menus etc.
- add a readme file to the HOL folder
- rename the HOL folders to shorter names for consistency

**Pull request merged**
