### PR TITLE
Adding "Installing MRP application manually" document

### PR DESCRIPTION
**Pull request by OguzPastirmaci**

### CODE REVIEW

**Comment by cicorias** [comment]
I suggest using a filename that doesn't have spaces in it and in Pascal notation, perhaps snake case (with dash separators).

**Comment by dtzar** [comment]
I agree with the filename Shawn has created.  This doc should be on just how to build the app - not deploy it.  Ideally with instructions using Linux, not just Windows.

**Comment by OguzPastirmaci** [comment]
I will update the file name.

About the second part, do you mean removing the instructions like creating the  vm on Linux etc? And if you mean building the app in Linux from the source, it should include installing Gradle and other dependencies in Linux. I will try to see if it's possible to do that with the current code.

Shawn, do you know if there's any platform specific parts in the source?


Windows Phone 8'imden gönderildi
________________________________

**Comment by cicorias** [comment]
I don't see any platform specific code or dependencies. I'll be compiling on Linux in the am, but as I recall Patrick had it compiling on Mac, not sure if he ran.

**Pull request closed without merging**
