### PR TITLE
Enhancement - Changing authentication for SSH

### PR DESCRIPTION
**Pull request by julienstroheker**
* Changing authentification on VM from Password to SSH
* Fixing issue #105

### CODE REVIEW

**Comment by jgardner04** [comment]
@julienstroheker I think we need to change the `SSH-MRP-Artifacts.ps1` file to use the SSH key instead of un/pw.  This means we will also need to change the PartsUnlimitedMRP.CD Deployment Variables docs.

**Comment by julienstroheker** [comment]
Yep indeed ! Do you have time to do it ? I can add you contributor on my repo ?
Thanks

**Comment by jgardner04** [comment]
@julienstroheker I can take a stab at it.

**Comment by julienstroheker** [comment]
https://github.com/julienstroheker/PartsUnlimitedMRP/invitations

**Comment by jgardner04** [comment]
@julienstroheker looking at it now.

**Comment by stephgou** [comment]
Hi, have you updated the SSH-MRP-Artifacts.ps1 file for SSH key instead of password ?
(I intend to use these lab for a workshop. So it may help me to save time is the job is already done...)

**Comment by DariuszPorowski** [comment]
I have the same Q as @stephgou...
@julienstroheker / @jgardner04 any updated in the SSH-MRP-Artifacts.ps1 file for SSH key instead of password?

**Pull request closed without merging**
